on:
  push:
    branches:
      - main
  pull_request:

jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # if we don't set this to 0 it can leave secrets in previus commits.
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}
          args: --debug --only-verified